### ISSUE TITLE
Manca il luogo nella form chiedi aiuto

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia_form#1]
Nella form "chiedi aiuto" https://ee.humanitarianresponse.info/x/#aozLp5mz manca l'informazione riguardante il luogo
emergenzeHack/covid19italia_segnalazioni#15

Allo stato attuale sembra scrivere solo le coordinate, se possibile aggiungerei anche il "nome del luogo" così da essere più precisi ed evitare di specificare la coordinata Z (l'altezza) :-)

**Comment by luciaroma** [comment]
Nel form va aggiunta una sezione "destinatari". Per esperienza su TCI, le descrizioni sono le più disparate e si rischia di perdere questa informazione che, nel caso covid19italia, è decisamente importante per orientare le segnalazione e fare il matching tra domanda e offerta di aiuto @avivace @tailot

**Comment by avivace** [comment]
@luciaroma una casella di testo "destinatari", va bene?

**Comment by luciaroma** [comment]
sì ottimo

**Comment by luciaroma** [comment]
direi con *obbligatorio :-)

**Comment by avivace** [comment]
@luciaroma così? https://ee.humanitarianresponse.info/x/#aozLp5mz

**Comment by avivace** [comment]
@tailot potrei aggiungere una casella di testo "nome luogo", ma potrebbe confondersi con quella in cui si "cerca il luogo" dalla quale in widget poi estrapola le coordinate...

**Comment by tailot** [comment]
@avivace se fa confusione no, importante che il form alla fine risulti decisivo e con i dati utili. Aggiungerei anche un bel disclaimer e ricorderei i numeri di emergenza 118 e pronto soccorso.
http://www.salute.gov.it/portale/temi/p2_6.jsp?lingua=italiano&id=1050&area=118%20Pronto%20Soccorso&menu=vuoto

Nel link sono presenti le regole per chiamare il 118 cruciali quando si è in panico.
Nel caso in cui ci sia qualche cosa che va fuori dalle ordinanze stabilite dallo stato chiamare anche i carabinieri 112.

**Comment by avivace** [comment]
@tailot Non saprei, tu cosa ne pensi? Possiamo metterli entrambi o vedere se si può implementare a livello di XLSForm una logica che semplicemente copia il campo della query posizione, se è effettivamente "esposto"
