### ISSUE TITLE
Modulo: Segnala bufale

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia_form#11]

**Comment by avivace** [comment]
https://github.com/emergenzeHack/covid19italia/issues/32

**Comment by tailot** [comment]
Attualmente la form di segnalazione bufale sembra puntare a quelle del terremoto:
Ne vedo una sulla vitamina C https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/3518

@avivace riesci a farle puntare sulle segnalazioni di covid19italia ?

**Comment by avivace** [comment]
@mfortini Questo era dovuto ai vecchi link, giusto? https://github.com/emergenzeHack/covid19italia/commit/e3de4df8bd9aaa589c4236f7deec2094d96a0356 dovrebbe risolvere

**Comment by aciulpan** [comment]
@avivace https://ee.humanitarianresponse.info/x/#ecZ2zzjJ
