### ISSUE TITLE
Correzioni web form

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia_form#16]
@avivace ecco le correzioni alla web form che suggerisco:

1. Nella form **Chiedi Aiuto** il campo link va in fondo
2. In **Dona Aiuto** aggiungere campo destinatari
3. In **Bufale** al posto di Nome inserire a Titolo
4. Rinominare Segnala **Smart Working** in Segnala Supporto Lavoro/Imprese. Dentro questa sostituisci Nome con Titolo e aggiungi Destinatari e Geolocalizzazione.
5. Rinomina **Segnala Dati** in Segnali Documenti/Dati. All’interno togli Nome e metti Titolo.
6. In Segnala **Iniziative Culturali** togli Nome e metti Titolo. Aggiungi: Destinatari, Geolocalizzazione, Soggetto Promotore.
7. In **Segnala Iniziative Solidali** togli Nome e metti Titolo. Aggiungi: Destinatari, Geolocalizzazione, Soggetto Promotore.
8. In **Segnala E-Learning** togli Nome e metti Titolo. Aggiungi: Destinatari, Geolocalizzazione, Soggetto Promotore.
9. In **Segnala Notizia** togli Nome e metti Titolo.

**Comment by RocknRollAllNight** [comment]
nella sezione form "Link (es: https://www.google.it)" non prende gli url... ho provato diversi formati (con https://, solo www o solo nome sito ecc..) ma da sempre messaggio di errore.

**Comment by aciulpan** [comment]
@RocknRollAllNight  Ho provato in questa form https://ee.humanitarianresponse.info/x/#hy7sHGP3 e sembra funzionare. Riesci a dirmi su quale form ti dava problemi ?

**Comment by avivace** [comment]
@cristigalas Ho sistemato e corretto 1, 2, 3, 4, 5 e 9 dei punti da te elencati. Aspetto decisioni per le iniziative.

**Comment by cristigalas** [comment]
Grazie! E gli altri punti 6-7-8? 
Segnalo poi che i bottoni della form adesso sono troppo stretti e non si leggono i testi fino in fondo.

**Comment by Saraveg** [comment]
Metto qua la proposta: 
 - iniziative solidali (levando privati e intendendo dell'associazionismo così come di aziende)
 - servizi pubblici

**Comment by avivace** [comment]
A livello di form, sono letteralmente identici, quindi io proporrei un modulo unico che chiede di fare una scelta all'inizio sulla natura della segnalazione

In base a questa scelta vengono poi pre-assegnate label diverse (di cui però bisogna ancora discutere) che definiscono poi come le segnalazioni verranno listate sul sito

**Comment by RocknRollAllNight** [comment]
> @RocknRollAllNight Ho provato in questa form https://ee.humanitarianresponse.info/x/#hy7sHGP3 e sembra funzionare. Riesci a dirmi su quale form ti dava problemi ?

sempre: https://ee.humanitarianresponse.info/x/#NsdBTg2O entrando dal sito su https://www.covid19italia.help/segnala/

**Comment by avivace** [comment]
@RocknRollAllNight A me sembra funzionare con questi test:

- https://www.w3schools.com/html/
- https://w3schools.com

Con quali link stai provando?

**Comment by RocknRollAllNight** [comment]
> @RocknRollAllNight A me sembra funzionare con questi test:
> 
> * https://www.w3schools.com/html/
> * https://w3schools.com
> 
> Con quali link stai provando?

vai è andata!

**Comment by avivace** [comment]
Grazie @RocknRollAllNight , se trovi dei link non accettati posta pure un Issue.
Vedete #18 per il nuovo form unico sulle segnalazioni delle iniziative

**Comment by avivace** [comment]
@cristigalas 
9. Io su "Segnala Notizia" vedo Titolo, non Nome, idem per il punto 5. Puoi controllare se è tutto okay?

Per quanto riguarda i "nomi" dei form, forse ti riferisci ai titoli dei bottoni, quelli li ho appena aggiornati. I titoli "interni" ai form invece erano già corretti come indicato

**Comment by cristigalas** [comment]
Ok @avivace ci siamo! Suggerisco solo di:
1. Cambiare **Segnala Iniziative** in **Segnala Iniziative e Servizi** (_modificare anche nella form interna_).
2. Dentro la form metti **ricreativa e culturale insieme**, al posto di ricreativa inserisci **Sostegno lavoro e imprese**.
3. In **Segnala Documenti/Dati** aggiungi campo **Chi** (nel senso di chi offre dati o documenti).

**Comment by avivace** [comment]
@cristigalas Fatto! Controlla fra qualche minuto che tutto sia a posto

**Comment by cristigalas** [comment]
> @cristigalas Fatto! Controlla fra qualche minuto che tutto sia a posto

Ci siamo! Grazie Antonio!
