### ISSUE TITLE
Link informativa nel form

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/covid19italia_form#23]
Non ho trovato altra issue che segnala il
problema: cliccando su segnalazione dati al fondo c’è un link “fittizio”
come recita la
scritta :)
![3B17431A-8F82-4445-97A0-46E365EF44E2](https://user-images.githubusercontent.com/6824007/76534608-00c63980-647a-11ea-8ac1-b4f889ef582e.jpeg)

**Comment by aciulpan** [comment]
@avivace @Saraveg Ho aggiornato questo form: vedete se vi piace così https://ee.humanitarianresponse.info/x/#aozLp5mz

**Comment by Saraveg** [comment]
mi sembra ottimo! grazie!

**Comment by aciulpan** [comment]
ok perfetto, allora aggiorno tutti gli altri form e chiudo la issue

**Comment by aciulpan** [comment]
Anzi, aspetteremo per il link all'informativa da accettare prima di fare modifiche
@Saraveg @avivace
