### ISSUE TITLE
In tante segnalazioni non si visualizzano tutti i campi 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia_form#25]
Ci sono ancora un po’ di segnalazioni di cui non si vedono tutti i campi ma solo titolo, tipo [questa](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/224 ) o [questa](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/183).
@mfortini @avivace Riuscite ad individuarle in modo automatico e sistemarle o dobbiamo segnalarvele una ad una?

**Comment by avivace** [comment]
https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/224 questo arriva malformato dal form e non riesco a capire come riprodurre..
Magari @mfortini ci sa dire di più

Il resto investigo e vediamo perchè i dati arrivavano rotti in quel modo

**Comment by MarcoAlici** [comment]
Se può aiutare, ho inviato io [questa](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/224), copia-incollando nel form il messaggio dal testo di un messaggio Whatsapp preso dal canale del Comune.

**Comment by cristigalas** [comment]
> Se può aiutare, ho inviato io [questa](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/224), copia-incollando nel form il messaggio dal testo di un messaggio Whatsapp preso dal canale del Comune.

Grazie Marco, ma non credo che il problema sia il copia-incolla... ci sono altre segnalazioni così ma @avivace ci sta lavorando, credo.

**Comment by avivace** [comment]
@cristigalas la 224 e la 183 adesso si vedono e dovremmo aver risolto un problema che ne impediva la visualizzazione.. Se avete altri esempi di non funzionanti investighiamo anche quelli

**Comment by cristigalas** [comment]
@avivace Queste ancora si vedono male:

https://covid19italia.help/issues/160
https://covid19italia.help/issues/158
https://covid19italia.help/issues/157
https://covid19italia.help/issues/156
https://covid19italia.help/issues/147
https://covid19italia.help/issues/311
https://covid19italia.help/issues/163
https://covid19italia.help/issues/164
https://covid19italia.help/issues/162
https://covid19italia.help/issues/337
https://covid19italia.help/issues/335
https://covid19italia.help/issues/293
https://covid19italia.help/issues/172
https://covid19italia.help/issues/153
https://covid19italia.help/issues/150
https://covid19italia.help/issues/116
https://covid19italia.help/issues/146
https://covid19italia.help/issues/95
https://covid19italia.help/issues/99
https://covid19italia.help/issues/151

Credo di averle censite tutte.

**Comment by avivace** [comment]
Grazie @cristigalas !

**Comment by cristigalas** [comment]
> Grazie @cristigalas !

Di nulla! Però nel frattempo se ne sono aggiunte altre... quando ho un attimo provo a censirle...

**Comment by avivace** [comment]
Grazie @cristigalas , da adesso puoi applicare la Label "da sistemare" a tutte le issue le cui segnalazioni si vedono male, così me le prendo in carico.

**Comment by cristigalas** [comment]
Ottimo! Lo dico anche alle altre! Grazie Antonio.
