### ISSUE TITLE
Validazione links

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia_form#3]
@jolsty

**Comment by aciulpan** [comment]
Trovato il modo per validare i form direttamente su KoboToolbox.
https://docs.opendatakit.org/form-logic/#id22

**Comment by avivace** [comment]
:tada:

Dovrebbe essere possibile creare le singole "Question" e poi importarle in vari form, sarebbe più comodo mantenerle (i.e. cambio la regola, tutte le question email si aggiornano nei vari form)

Ti risulta?

**Comment by aciulpan** [comment]
Non ho trovato il modo per farlo, hai notato qualcosa che ti ha fatto pensare che sia possibile?

**Comment by claudiamazzantiact** [comment]
Ciao, segnalo ancora un problema sul form per accettare link tipo questo: "https://public.tableau.com/profile/riccardo.saporiti?fbclid=IwAR0YvTDOXO0zzQ1ODwOMlDWlc8ghtnmZt4-2Mz4j3pEgGNNkszZwl3LMuZM#!/vizhome/MappanegoziGallaratecoronavirus/Dashboard1?publish=yes"

Si genera messaggio: Per favore inserisci un link valido.

**Comment by drizzt** [comment]
> Ciao, segnalo ancora un problema sul form per accettare link tipo questo: "https://public.tableau.com/profile/riccardo.saporiti?fbclid=IwAR0YvTDOXO0zzQ1ODwOMlDWlc8ghtnmZt4-2Mz4j3pEgGNNkszZwl3LMuZM#!/vizhome/MappanegoziGallaratecoronavirus/Dashboard1?publish=yes"
> 
> Si genera messaggio: Per favore inserisci un link valido.

In teoria quello non è un link valido in quanto ha ? specificato 2 volte. Levando ?fbclid=XXX diventa un link valido. ed è cosa buona e giusta levare fbclid, in generale, in quanto viene usato per fare analitica e cercare di capire chi ha cliccato. metterlo qui rompe le loro metriche:

https://public.tableau.com/profile/riccardo.saporiti#!/vizhome/MappanegoziGallaratecoronavirus/Dashboard1?publish=yes

**Comment by claudiamazzantiact** [comment]
Grazie!

**Comment by avivace** [comment]
Se credete che questa "validazione" crei più problemi che altro possiamo accettare *tutti* i link e procedere noi internamente a pulirli preliminarmente e poi lasciare il lavoro a chi fa la review delle issue, con il risultato però di avere altro lavoro manuale

@drizzt  Anche se ?param1=1?param2=2 è invalido, si potrebbe fare in modo di accettarlo comunque (i browser li accettano comunque)
