### ISSUE TITLE
Link not accepted

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia_form#37]
http://www.cm-funchal.pt/pt/not%C3%ADciaspt/7096-a-c%C3%A2mara-municipal-do-funchal-promove,-a-partir-desta-quarta-feira,-dia-8-de-abril,-a-venda-itinerante-de-fruta-e-legumes-pelo-concelho,-em-mais-uma-medida-no-sentido-de-apoiar-os-agricultores-regionais-a-escoar-os-seus-produtos-nesta-altura-de-crise.html is not accepted

Any idea @Jolsty ?

**Comment by aciulpan** [comment]
@avivace There are commas in the link. Bad idea

**Comment by avivace** [comment]
Removing commas seems to make it work
